version: '3'

services:
    postgres:
        image: 'postgres:15.4'
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: project
        ports:
            - 5432:5432
