const UserDetailsTableColumn = {
    ID: 'id',
    USER_ID: 'userId',
    IS_APPROVED: 'isApproved',
    DENIED_REASON: 'deniedReason',
    IS_HIRED: 'isHired',
    PROFILE_NAME: 'profileName',
    SALARY_EXPECTATION: 'salaryExpectation',
    HIRED_SALARY: 'hiredSalary',
    JOB_TITLE: 'jobTitle',
    LOCATION: 'location',
    EXPERIENCE_YEARS: 'experienceYears',
    EMPLOYMENT_TYPE: 'employmentType',
    DESCRIPTION: 'description',
    ENGLISH_LEVEL: 'englishLevel',
    NOT_CONSIDERED: 'notConsidered',
    PREFERRED_LANGUAGES: 'preferredLanguages',
    PROJECT_LINKS: 'projectLinks',
    PHOTO_ID: 'photoId',
    FULL_NAME: 'fullName',
    PHONE: 'phone',
    LINKEDIN_LINK: 'linkedinLink',
    COMPANY_NAME: 'companyName',
    COMPANY_LOGO_ID: 'companyLogoId',
    COMPANY_WEBSITE: 'companyWebsite',
    EMPLOYER_POSITION: 'employerPosition',
    CV_ID: 'cvId',
} as const;

export { UserDetailsTableColumn };
