const mockCandidates = [
    {
        profileName: 'JS dev',
        salaryExpectation: 3000,
        projectLinks: [],
        location: 'France',
        englishLevel: 'C1 Advanced',
        badges: ['1', '2', '5', '4', '3'],
        preferredLanguages: ['English', 'French'],
        description:
            'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes1 on purpose (injected humour and the like)',
        hardSkills: [
            { value: 'React', label: 'React' },
            { value: 'CSS', label: 'CSS' },
            { value: 'Python', label: 'Python' },
            { value: 'Java', label: 'Java' },
        ],
        experienceYears: 3,
        jobTitle: 'JS',
        fullName: 'Test Test',
        phone: '+380999999998',
        employmentType: [],
        notConsidered: ['gamedev', 'crypto'],
        cvId: 'aaa11111',
        email: 'a@gmail.com',
    },
    {
        profileName: '.Net dev',
        salaryExpectation: 50,
        projectLinks: [],
        location: 'Ukraine',
        englishLevel: 'B1 Intermediate',
        badges: ['1', '2', '5', '4', '3'],
        preferredLanguages: ['English', 'French'],
        description:
            'Reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)',
        hardSkills: [
            { value: 'React', label: 'React' },
            { value: 'Node.js', label: 'Node.js' },
            { value: 'JavaScript', label: 'JavaScript' },
        ],
        experienceYears: 3,
        jobTitle: 'JS',
        fullName: 'Test Test',
        phone: '+380999998899',
        employmentType: [],
        notConsidered: ['gamedev', 'crypto'],
        cvId: 'aaa11122',
        email: 'b@gmail.com',
    },
    {
        profileName: 'QA',
        salaryExpectation: 600,
        projectLinks: [],
        location: 'Ukraine',
        englishLevel: 'C1 Advanced',
        badges: ['1', '2', '5', '4', '3'],
        preferredLanguages: ['English', 'French'],
        description:
            'looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)',
        hardSkills: [{ value: 'React', label: 'React' }],
        experienceYears: 3,
        jobTitle: 'JS',
        fullName: 'Test Test',
        phone: '+380977999999',
        employmentType: [],
        notConsidered: ['gamedev', 'crypto'],
        cvId: 'aaa11133',
        email: 'c2@gmail.com',
    },
    {
        profileName: 'QA',
        salaryExpectation: 9999,
        projectLinks: [],
        location: 'Ukraine',
        englishLevel: 'B1 Intermidiate',
        badges: ['1', '2', '5', '4', '3'],
        preferredLanguages: ['English', 'French'],
        description:
            'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)',
        hardSkills: [{ value: 'React', label: 'React' }],
        experienceYears: 3,
        jobTitle: 'JS',
        fullName: 'Test Test',
        phone: '+380999999999',
        employmentType: [],
        notConsidered: ['gamedev', 'crypto'],
        cvId: 'aaa11144',
        email: 'c4@gmail.com',
    },
    {
        profileName: 'QA',
        salaryExpectation: 50,
        projectLinks: [],
        location: 'Ukraine',
        englishLevel: 'B1 Intermediate',
        badges: ['1', '2', '5', '4', '3'],
        preferredLanguages: ['English', 'French'],
        description:
            'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)',
        hardSkills: [{ value: 'React', label: 'React' }],
        experienceYears: 3,
        jobTitle: 'JS',
        fullName: 'Test Test',
        phone: '+380999999999',
        employmentType: [],
        notConsidered: ['gamedev', 'crypto'],
        cvId: 'aaa11155',
        email: 'c5@gmail.com',
    },
];

export { mockCandidates };
