const hardSkillsSeed = [
    'JavaScript',
    'Python',
    'Java',
    'C++',
    'Ruby',
    'PHP',
    'Swift',
    'Go',
    'Kotlin',
    'HTML/CSS',
    'React.js',
    'Angular',
    'Node.js',
    'SQL Database Management',
    'NoSQL Database Management',
    'Database Design',
    'Cloud Computing',
    'DevOps',
    'Cybersecurity',
    'Network Administration',
    'Big Data',
    'Machine Learning',
    'Artificial Intelligence',
    'Web Development',
    'Mobile App Development',
    'API Development',
    'Software Testing',
    'Project Management',
    'UI/UX Design',
    'Front-end Development',
    'Back-end Development',
    'Full-stack Development',
    'Blockchain Development',
    'Data Science',
    'IT Support',
    'Scripting',
    'IT Security Compliance',
    'Automation',
    'Data Analytics',
    'Cloud Security',
    'RESTful APIs',
    'System Administration',
    'Continuous Integration/Continuous Deployment (CI/CD)',
    'Marketing',
    'Project Management',
    'Product Management',
    'SEO',
    'AWS',
    'Azure',
    'GCP',
    'Slack',
    'Miro',
    'Git',
    'Figma',
    'Microsoft Office Suite',
    'G Suite',
    'Dropbox',
    'Trello',
    'Asana',
    'JIRA',
    'Confluence',
    'Basecamp',
    'Git',
];

export { hardSkillsSeed };
