const ProfileStepValidationRule = {
    MIN_PROFILE_NAME_LENGTH: 2,
    MAX_PROFILE_NAME_LENGTH: 50,
    MIN_SALARY_EXPECTATION: 1,
    MAX_SALARY_EXPECTATION: 9999,
    MIN_EXPERIENCE_DESCRIPTION_LENGTH: 100,
    MAX_EXPERIENCE_DESCRIPTION_LENGTH: 2500,
    MIN_YEARS_OF_EXPERIENCE: 0,
    MAX_YEARS_OF_EXPERIENCE: 5.5,
    YEARS_OF_EXPERIENCE_STEP: 0.5,
    EMPLOYMENT_TYPES_MIN_LENGTH: 1,
} as const;

export { ProfileStepValidationRule };
